Merge docker into main
fireant-bot/fireant pull request #16
Opened 2021-04-09 17:08 UTC by jamie-meyer

Docker branch contains the latest changes for the fireant program. The main branch should actually contain all of these changes, but we got stuck with making changes on docker branch. Should be ported for consistency and maintainability.

2021-04-09 17:24 UTC, lewismc requested changes
Thanks @jamie-meyer and anyone else who contributed to this. I think we should remove whitespace and then merge. We can then go back and improve with documentation. We can also run deepsource on the code and fix any issues identified there.

2021-04-09 17:24 UTC, lewismc commented on main.py
> +
Please remove all whitespace.

2021-04-09 17:35 UTC, jamie-meyer commented on main.py
> +
All whitespace has been removed.

2021-04-10 16:31 UTC, lewismc commented
@jamie-meyer thanks for updating the PR. When I said please remove whitespace I should have asked you to apply this to the entire pull request. Excess whitespace exists all over the place. Please remove it where you can. Thanks

2021-04-10 16:32 UTC, lewismc commented
actually @jamie-meyer please just create another issue to address the whitespace issue. Thanks

2021-04-10 16:32 UTC, merged