Add Jenkinsfile
fireant-bot/fireant pull request #6
Opened 2021-04-01 23:12 UTC by mjemnawaz

2021-04-01 23:45 UTC, lewismc commented
Hi @mjemnawaz I can read the code but can please explain which task you want to execute as part of the CI?
Also has this just to be run nightly or do you have some other intentions? 
thanks

2021-04-02 00:05 UTC, mjemnawaz commented
@lewismc Right now I'm running all 3 stages that are uncommented in the Jenkinsfile, and I'm using a webhook so that it runs everytime someone pushes to GitHub, plus it also runs every 24 hours.

2021-04-02 13:51 UTC, lewismc commented
OK great @mjemnawaz I'm trying to set this up right now. Thank you

2021-04-02 15:21 UTC, lewismc commented on Jenkinsfile
> +        registry = 'fireantci/fireant'
Please update

2021-04-02 15:22 UTC, lewismc requested changes
Good work @mjemnawaz

2021-04-02 15:22 UTC, lewismc commented on Jenkinsfile
> +/*
Actually @mjemnawaz please provide a README for this entire PR. Thank you

2021-04-07 01:45 UTC, merged